/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CountryCode = string;
export interface CountryEntryPublic {
  'status' : TravelStatus,
  'code' : CountryCode,
}
export type StateCode = string;
export interface StateEntryPublic {
  'status' : TravelStatus,
  'code' : StateCode,
}
export interface Stats {
  'totalTrips' : bigint,
  'totalWishlisted' : bigint,
  'totalDaysAbroad' : bigint,
  'totalVisited' : bigint,
  'totalLivedIn' : bigint,
}
export type TravelStatus = { 'wishlisted' : null } |
  { 'visited' : null } |
  { 'lived_in' : null };
export type TripId = bigint;
export interface TripPublic {
  'id' : TripId,
  'endDate' : bigint,
  'countryCode' : CountryCode,
  'notes' : [] | [string],
  'startDate' : bigint,
}
export interface _SERVICE {
  'addTrip' : ActorMethod<[CountryCode, bigint, bigint, [] | [string]], TripId>,
  'deleteTrip' : ActorMethod<[TripId], boolean>,
  'getStats' : ActorMethod<[], Stats>,
  'listCountries' : ActorMethod<[], Array<CountryEntryPublic>>,
  'listStates' : ActorMethod<[], Array<StateEntryPublic>>,
  'listTrips' : ActorMethod<[], Array<TripPublic>>,
  'removeCountry' : ActorMethod<[CountryCode], undefined>,
  'removeState' : ActorMethod<[StateCode], undefined>,
  'setCountry' : ActorMethod<[CountryCode, TravelStatus], undefined>,
  'setState' : ActorMethod<[StateCode, TravelStatus], undefined>,
  'updateTrip' : ActorMethod<[TripId, bigint, bigint, [] | [string]], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];