/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CountryCode = IDL.Text;
export const TripId = IDL.Nat;
export const Stats = IDL.Record({
  'totalTrips' : IDL.Nat,
  'totalWishlisted' : IDL.Nat,
  'totalDaysAbroad' : IDL.Nat,
  'totalVisited' : IDL.Nat,
  'totalLivedIn' : IDL.Nat,
});
export const TravelStatus = IDL.Variant({
  'wishlisted' : IDL.Null,
  'visited' : IDL.Null,
  'lived_in' : IDL.Null,
});
export const CountryEntryPublic = IDL.Record({
  'status' : TravelStatus,
  'code' : CountryCode,
});
export const StateCode = IDL.Text;
export const StateEntryPublic = IDL.Record({
  'status' : TravelStatus,
  'code' : StateCode,
});
export const TripPublic = IDL.Record({
  'id' : TripId,
  'endDate' : IDL.Int,
  'countryCode' : CountryCode,
  'notes' : IDL.Opt(IDL.Text),
  'startDate' : IDL.Int,
});

export const idlService = IDL.Service({
  'addTrip' : IDL.Func(
      [CountryCode, IDL.Int, IDL.Int, IDL.Opt(IDL.Text)],
      [TripId],
      [],
    ),
  'deleteTrip' : IDL.Func([TripId], [IDL.Bool], []),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'listCountries' : IDL.Func([], [IDL.Vec(CountryEntryPublic)], ['query']),
  'listStates' : IDL.Func([], [IDL.Vec(StateEntryPublic)], ['query']),
  'listTrips' : IDL.Func([], [IDL.Vec(TripPublic)], ['query']),
  'removeCountry' : IDL.Func([CountryCode], [], []),
  'removeState' : IDL.Func([StateCode], [], []),
  'setCountry' : IDL.Func([CountryCode, TravelStatus], [], []),
  'setState' : IDL.Func([StateCode, TravelStatus], [], []),
  'updateTrip' : IDL.Func(
      [TripId, IDL.Int, IDL.Int, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CountryCode = IDL.Text;
  const TripId = IDL.Nat;
  const Stats = IDL.Record({
    'totalTrips' : IDL.Nat,
    'totalWishlisted' : IDL.Nat,
    'totalDaysAbroad' : IDL.Nat,
    'totalVisited' : IDL.Nat,
    'totalLivedIn' : IDL.Nat,
  });
  const TravelStatus = IDL.Variant({
    'wishlisted' : IDL.Null,
    'visited' : IDL.Null,
    'lived_in' : IDL.Null,
  });
  const CountryEntryPublic = IDL.Record({
    'status' : TravelStatus,
    'code' : CountryCode,
  });
  const StateCode = IDL.Text;
  const StateEntryPublic = IDL.Record({
    'status' : TravelStatus,
    'code' : StateCode,
  });
  const TripPublic = IDL.Record({
    'id' : TripId,
    'endDate' : IDL.Int,
    'countryCode' : CountryCode,
    'notes' : IDL.Opt(IDL.Text),
    'startDate' : IDL.Int,
  });
  
  return IDL.Service({
    'addTrip' : IDL.Func(
        [CountryCode, IDL.Int, IDL.Int, IDL.Opt(IDL.Text)],
        [TripId],
        [],
      ),
    'deleteTrip' : IDL.Func([TripId], [IDL.Bool], []),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'listCountries' : IDL.Func([], [IDL.Vec(CountryEntryPublic)], ['query']),
    'listStates' : IDL.Func([], [IDL.Vec(StateEntryPublic)], ['query']),
    'listTrips' : IDL.Func([], [IDL.Vec(TripPublic)], ['query']),
    'removeCountry' : IDL.Func([CountryCode], [], []),
    'removeState' : IDL.Func([StateCode], [], []),
    'setCountry' : IDL.Func([CountryCode, TravelStatus], [], []),
    'setState' : IDL.Func([StateCode, TravelStatus], [], []),
    'updateTrip' : IDL.Func(
        [TripId, IDL.Int, IDL.Int, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };