/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TripPublic {
    id: TripId;
    endDate: bigint;
    countryCode: CountryCode;
    notes?: string;
    startDate: bigint;
}
export interface StateEntryPublic {
    status: TravelStatus;
    code: StateCode;
}
export type CountryCode = string;
export type TripId = bigint;
export interface Stats {
    totalTrips: bigint;
    totalWishlisted: bigint;
    totalDaysAbroad: bigint;
    totalVisited: bigint;
    totalLivedIn: bigint;
}
export type StateCode = string;
export interface CountryEntryPublic {
    status: TravelStatus;
    code: CountryCode;
}
export enum TravelStatus {
    wishlisted = "wishlisted",
    visited = "visited",
    lived_in = "lived_in"
}
export interface backendInterface {
    addTrip(countryCode: CountryCode, startDate: bigint, endDate: bigint, notes: string | null): Promise<TripId>;
    deleteTrip(id: TripId): Promise<boolean>;
    getStats(): Promise<Stats>;
    listCountries(): Promise<Array<CountryEntryPublic>>;
    listStates(): Promise<Array<StateEntryPublic>>;
    listTrips(): Promise<Array<TripPublic>>;
    removeCountry(code: CountryCode): Promise<void>;
    removeState(code: StateCode): Promise<void>;
    setCountry(code: CountryCode, status: TravelStatus): Promise<void>;
    setState(code: StateCode, status: TravelStatus): Promise<void>;
    updateTrip(id: TripId, startDate: bigint, endDate: bigint, notes: string | null): Promise<boolean>;
}
import type { CountryCode as _CountryCode, CountryEntryPublic as _CountryEntryPublic, StateCode as _StateCode, StateEntryPublic as _StateEntryPublic, TravelStatus as _TravelStatus, TripId as _TripId, TripPublic as _TripPublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTrip(arg0: CountryCode, arg1: bigint, arg2: bigint, arg3: string | null): Promise<TripId> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrip(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrip(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deleteTrip(arg0: TripId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrip(arg0);
            return result;
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async listCountries(): Promise<Array<CountryEntryPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCountries();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCountries();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStates(): Promise<Array<StateEntryPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStates();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStates();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTrips(): Promise<Array<TripPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTrips();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTrips();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeCountry(arg0: CountryCode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCountry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCountry(arg0);
            return result;
        }
    }
    async removeState(arg0: StateCode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeState(arg0);
            return result;
        }
    }
    async setCountry(arg0: CountryCode, arg1: TravelStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCountry(arg0, to_candid_TravelStatus_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCountry(arg0, to_candid_TravelStatus_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setState(arg0: StateCode, arg1: TravelStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setState(arg0, to_candid_TravelStatus_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setState(arg0, to_candid_TravelStatus_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTrip(arg0: TripId, arg1: bigint, arg2: bigint, arg3: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrip(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrip(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_CountryEntryPublic_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CountryEntryPublic): CountryEntryPublic {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_StateEntryPublic_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StateEntryPublic): StateEntryPublic {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TravelStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TravelStatus): TravelStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_TripPublic_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripPublic): TripPublic {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TripId;
    endDate: bigint;
    countryCode: _CountryCode;
    notes: [] | [string];
    startDate: bigint;
}): {
    id: TripId;
    endDate: bigint;
    countryCode: CountryCode;
    notes?: string;
    startDate: bigint;
} {
    return {
        id: value.id,
        endDate: value.endDate,
        countryCode: value.countryCode,
        notes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.notes)),
        startDate: value.startDate
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TravelStatus;
    code: _CountryCode;
}): {
    status: TravelStatus;
    code: CountryCode;
} {
    return {
        status: from_candid_TravelStatus_n5(_uploadFile, _downloadFile, value.status),
        code: value.code
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TravelStatus;
    code: _StateCode;
}): {
    status: TravelStatus;
    code: StateCode;
} {
    return {
        status: from_candid_TravelStatus_n5(_uploadFile, _downloadFile, value.status),
        code: value.code
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wishlisted: null;
} | {
    visited: null;
} | {
    lived_in: null;
}): TravelStatus {
    return "wishlisted" in value ? TravelStatus.wishlisted : "visited" in value ? TravelStatus.visited : "lived_in" in value ? TravelStatus.lived_in : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TripPublic>): Array<TripPublic> {
    return value.map((x)=>from_candid_TripPublic_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CountryEntryPublic>): Array<CountryEntryPublic> {
    return value.map((x)=>from_candid_CountryEntryPublic_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StateEntryPublic>): Array<StateEntryPublic> {
    return value.map((x)=>from_candid_StateEntryPublic_n8(_uploadFile, _downloadFile, x));
}
function to_candid_TravelStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TravelStatus): _TravelStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TravelStatus): {
    wishlisted: null;
} | {
    visited: null;
} | {
    lived_in: null;
} {
    return value == TravelStatus.wishlisted ? {
        wishlisted: null
    } : value == TravelStatus.visited ? {
        visited: null
    } : value == TravelStatus.lived_in ? {
        lived_in: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
